#!/bin/bash
CONVERT="./convert"
COMMUNITY="./community"
FLAG_INPUT="-i"
FLAG_OUTPUT="-o"
FLAG_VERBOSITY="-v"
FLAG_LEVEL=-"-l"
LEVEL="-1"
METRIC="-modularity"
EXT_CONV=".pairs"
EXT_COMM=".bin"
EXT_HIER=".tree"
INPUT_PATH="../../input/"

NAME=(
	"adjnoun"
	"amazon0302"
	"amazon0312"
	"amazon0505"
	"amazon0601"
	"as-22july06"
	"com-amazon.ungraph"
	"com-dblp.ungraph"
	"dolphins"
	"email-Enron"
	"karate"
	"loc-gowalla_edges"
	"oregon1_010414"
	"oregon1_010421"
	"oregon1_010428"
	"oregon1_010505"
	"oregon1_010512"
	"oregon1_010519"
	"p2p-Gnutella04"
	"p2p-Gnutella05"
	"p2p-Gnutella06"
	"p2p-Gnutella08"
	"p2p-Gnutella25"
	"p2p-Gnutella30"
	"p2p-Gnutella31"
	"polbooks"
	"power"
	"roadNet-CA"
	"roadNet-PA"
	"roadNet-TX"
	"soc-LiveJournal1"
	"soc-pokec-relationships"
	"web-NorteDame"
	"web-Stanford"
)

for name in "${NAME[@]}"
do
	CONVERT_COMMAND="$CONVERT $FLAG_INPUT ${INPUT_PATH}${name}${EXT_CONV} $FLAG_OUTPUT ${INPUT_PATH}${name}${EXT_COMM} -d"
	COMMUNITY_COMMAND="${COMMUNITY}${METRIC} ${INPUT_PATH}${name}${EXT_COMM} $FLAG_LEVEL $LEVEL $FLAG_VERBOSITY > ${INPUT_PATH}${name}${METRIC}${EXT_HIER}"
	echo $CONVERT_COMMAND
	$CONVERT_COMMAND
	
done